name: list_model_cubit_repo_api
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  flutter_bloc: ^6.1.1
  dio: ^3.0.10
  conditional_builder: ^1.0.2

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-ExtraLight.ttf
    - family: Modak
      fonts:
        - asset: fonts/Modak.ttf
    - family: SourceSansProLight
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf